#!/usr/bin/env python3
"""
build_project.py — Volts Lab packager

This script packages the complete Volts Lab full-stack project
(the `volts_backend/` Django app and `volts-frontend/` React app that
ship alongside this script) into a single downloadable archive:

    volts-lab-django-fullstack.zip

Usage:
    python build_project.py

It walks both project directories, skips build artifacts / caches /
virtual envs / node_modules (regenerated by `pip install` and
`npm install` respectively), and writes everything else into the zip
with the same relative folder structure — so unzipping reproduces the
exact tree described in the project README.
"""

import os
import zipfile
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
OUTPUT_ZIP = SCRIPT_DIR / "volts-lab-django-fullstack.zip"

INCLUDE_DIRS = ["volts_backend", "volts-frontend"]
INCLUDE_ROOT_FILES = ["README.md"]

# Directories we never want inside the shipped archive
EXCLUDE_DIR_NAMES = {
    "__pycache__", "node_modules", "dist", "build",
    ".git", ".venv", "venv", ".vite",
}

# File suffixes / exact names to skip
EXCLUDE_FILE_NAMES = {"db.sqlite3", ".DS_Store"}
EXCLUDE_FILE_SUFFIXES = {".pyc"}


def should_skip_dir(dirname: str) -> bool:
    return dirname in EXCLUDE_DIR_NAMES


def should_skip_file(filename: str) -> bool:
    if filename in EXCLUDE_FILE_NAMES:
        return True
    if any(filename.endswith(suf) for suf in EXCLUDE_FILE_SUFFIXES):
        return True
    return False


def add_tree_to_zip(zf: zipfile.ZipFile, root: Path, arc_prefix: str):
    for current_root, dirnames, filenames in os.walk(root):
        # prune excluded directories in-place so os.walk doesn't descend into them
        dirnames[:] = [d for d in dirnames if not should_skip_dir(d)]

        for fname in filenames:
            if should_skip_file(fname):
                continue
            full_path = Path(current_root) / fname
            rel_path = full_path.relative_to(root)
            arcname = f"{arc_prefix}/{rel_path.as_posix()}"
            zf.write(full_path, arcname)


def main():
    if OUTPUT_ZIP.exists():
        OUTPUT_ZIP.unlink()

    file_count = 0
    with zipfile.ZipFile(OUTPUT_ZIP, "w", zipfile.ZIP_DEFLATED) as zf:
        for dirname in INCLUDE_DIRS:
            src = SCRIPT_DIR / dirname
            if not src.exists():
                print(f"  ! Skipping missing directory: {dirname}")
                continue
            add_tree_to_zip(zf, src, dirname)

        for fname in INCLUDE_ROOT_FILES:
            src = SCRIPT_DIR / fname
            if src.exists():
                zf.write(src, fname)

        file_count = len(zf.namelist())

    size_kb = OUTPUT_ZIP.stat().st_size / 1024
    print(f"Packaged {file_count} files into {OUTPUT_ZIP.name} ({size_kb:.1f} KB)")
    print("Unzip anywhere, then follow README.md to run the backend and frontend.")


if __name__ == "__main__":
    main()
