from django.core.management.base import BaseCommand
from problems.models import Question

SEED_QUESTIONS = [
    # ---------------- BASIC ELECTRICAL ----------------
    dict(title="Ohm's Law Basics", topic='BASIC_ELECTRICAL', problem_type='THEORY',
         difficulty='EASY',
         question_text="Which equation correctly represents Ohm's Law for a resistor?",
         option_a='V = IR', option_b='V = I/R', option_c='V = I + R', option_d='I = VR',
         correct_option='A',
         explanation="Ohm's Law states that voltage across a resistor is directly proportional "
                     "to the current through it, with resistance as the constant of proportionality: V = IR.",
         formula_hint='V = IR', points=10),
    dict(title='Series Resistor Current', topic='BASIC_ELECTRICAL', problem_type='NUMERICAL',
         difficulty='EASY',
         question_text='A 12V battery is connected across two resistors of $4\\Omega$ and $2\\Omega$ '
                        'in series. Find the current flowing in the circuit.',
         given_values='V = 12V, R1 = 4Ω, R2 = 2Ω',
         option_a='1 A', option_b='2 A', option_c='3 A', option_d='6 A',
         correct_option='B',
         explanation='Total resistance R = R1 + R2 = 6Ω. Current I = V/R = 12/6 = 2A.',
         formula_hint='R_total = R1 + R2, I = V / R_total', points=10),
    dict(title='Power Dissipation', topic='BASIC_ELECTRICAL', problem_type='NUMERICAL',
         difficulty='MEDIUM',
         question_text='A resistor of $10\\Omega$ carries a current of 3A. Calculate the power dissipated.',
         given_values='R = 10Ω, I = 3A',
         option_a='30 W', option_b='60 W', option_c='90 W', option_d='120 W',
         correct_option='C',
         explanation='P = I²R = (3)² × 10 = 9 × 10 = 90W.',
         formula_hint='P = I²R', points=15),

    # ---------------- CIRCUIT THEORY ----------------
    dict(title="Kirchhoff's Current Law", topic='CIRCUIT_THEORY', problem_type='THEORY',
         difficulty='EASY',
         question_text="Kirchhoff's Current Law (KCL) is based on the conservation of:",
         option_a='Energy', option_b='Charge', option_c='Momentum', option_d='Voltage',
         correct_option='B',
         explanation='KCL states the algebraic sum of currents at a node is zero, which follows '
                     'directly from the conservation of electric charge.',
         formula_hint='ΣI_in = ΣI_out', points=10),
    dict(title='Thevenin Equivalent Resistance', topic='CIRCUIT_THEORY', problem_type='NUMERICAL',
         difficulty='MEDIUM',
         question_text='Two resistors of $6\\Omega$ and $3\\Omega$ are connected in parallel across '
                        'a source. Find the Thevenin equivalent resistance seen from the terminals '
                        '(source replaced by its internal short).',
         given_values='R1 = 6Ω, R2 = 3Ω',
         option_a='1 Ω', option_b='2 Ω', option_c='4.5 Ω', option_d='9 Ω',
         correct_option='B',
         explanation='For parallel resistors: R_th = (R1×R2)/(R1+R2) = (6×3)/9 = 18/9 = 2Ω.',
         formula_hint='R_parallel = (R1 R2) / (R1 + R2)', points=15),
    dict(title='Superposition Theorem', topic='CIRCUIT_THEORY', problem_type='THEORY',
         difficulty='MEDIUM',
         question_text='The Superposition Theorem is applicable only to circuits that are:',
         option_a='Purely resistive', option_b='Linear and bilateral',
         option_c='Non-linear', option_d='Time-varying only',
         correct_option='B',
         explanation='Superposition applies only to linear, bilateral circuits, since it relies on '
                     'the additive property that only holds for linear elements.',
         formula_hint='Valid only for linear circuits', points=15),

    # ---------------- ELECTRONICS AND VLSI ----------------
    dict(title='MOSFET Regions of Operation', topic='ELECTRONICS_VLSI', problem_type='THEORY',
         difficulty='MEDIUM',
         question_text='An NMOS transistor operates in the saturation region when:',
         option_a='V_GS < V_th', option_b='V_DS < V_GS - V_th',
         option_c='V_DS ≥ V_GS - V_th', option_d='V_GS = 0',
         correct_option='C',
         explanation='Saturation occurs when V_DS ≥ V_GS − V_th (i.e., the channel is pinched off '
                     'near the drain), giving the transistor its current-source-like behavior.',
         formula_hint='V_DS ≥ V_GS − V_th for saturation', points=15),
    dict(title='Diode Forward Voltage Drop', topic='ELECTRONICS_VLSI', problem_type='NUMERICAL',
         difficulty='EASY',
         question_text='A silicon diode with forward voltage drop 0.7V is in series with a $330\\Omega$ '
                        'resistor across a 5V source. Find the diode current.',
         given_values='V = 5V, V_D = 0.7V, R = 330Ω',
         option_a='6.5 mA', option_b='10 mA', option_c='13 mA', option_d='15.2 mA',
         correct_option='C',
         explanation='I = (V − V_D)/R = (5 − 0.7)/330 = 4.3/330 ≈ 0.01303 A ≈ 13 mA.',
         formula_hint='I = (V_source − V_diode) / R', points=15),
    dict(title='CMOS Inverter Property', topic='ELECTRONICS_VLSI', problem_type='THEORY',
         difficulty='HARD',
         question_text='The main advantage of a CMOS inverter over an NMOS-only inverter is:',
         option_a='Higher static power dissipation', option_b='Near-zero static power dissipation',
         option_c='Smaller area', option_d='Higher noise sensitivity',
         correct_option='B',
         explanation='In steady state, one of the two CMOS transistors is always off, so ideally no '
                     'DC current flows, giving near-zero static power dissipation.',
         formula_hint='Only one of PMOS/NMOS conducts in steady state', points=20),

    # ---------------- ELECTRICAL MACHINES ----------------
    dict(title='DC Motor Back EMF', topic='ELECTRICAL_MACHINES', problem_type='THEORY',
         difficulty='MEDIUM',
         question_text='The back EMF of a DC motor is directly proportional to:',
         option_a='Armature resistance only', option_b='Speed and flux',
         option_c='Supply voltage only', option_d='Field resistance only',
         correct_option='B',
         explanation='Back EMF E_b = kΦN, i.e., it is proportional to the product of flux (Φ) and '
                     'speed (N), where k is a machine constant.',
         formula_hint='E_b = kΦN', points=15),
    dict(title='Transformer Turns Ratio', topic='ELECTRICAL_MACHINES', problem_type='NUMERICAL',
         difficulty='EASY',
         question_text='A transformer has 200 primary turns and 800 secondary turns. If the primary '
                        'voltage is 230V, find the secondary voltage.',
         given_values='N1 = 200, N2 = 800, V1 = 230V',
         option_a='57.5 V', option_b='230 V', option_c='460 V', option_d='920 V',
         correct_option='D',
         explanation='V2/V1 = N2/N1 → V2 = 230 × (800/200) = 230 × 4 = 920V.',
         formula_hint='V2/V1 = N2/N1', points=10),
    dict(title='Slip of Induction Motor', topic='ELECTRICAL_MACHINES', problem_type='NUMERICAL',
         difficulty='MEDIUM',
         question_text='A 3-phase induction motor has a synchronous speed of 1500 RPM and runs at '
                        '1440 RPM. Calculate the slip.',
         given_values='Ns = 1500 RPM, N = 1440 RPM',
         option_a='2%', option_b='4%', option_c='6%', option_d='8%',
         correct_option='B',
         explanation='Slip s = (Ns − N)/Ns × 100 = (1500 − 1440)/1500 × 100 = 60/1500 × 100 = 4%.',
         formula_hint='s = (Ns − N)/Ns × 100', points=15),

    # ---------------- POWER ELECTRONICS ----------------
    dict(title='Thyristor Turn-Off', topic='POWER_ELECTRONICS', problem_type='THEORY',
         difficulty='MEDIUM',
         question_text='An SCR (thyristor) can be turned OFF by:',
         option_a='Increasing gate current', option_b='Reducing anode current below holding current',
         option_c='Increasing anode voltage', option_d='Applying negative gate pulse',
         correct_option='B',
         explanation='Once triggered, the gate loses control; an SCR turns off only when the anode '
                     'current falls below the holding current (natural or forced commutation).',
         formula_hint='I_anode < I_holding → turns off', points=15),
    dict(title='Buck Converter Output Voltage', topic='POWER_ELECTRONICS', problem_type='NUMERICAL',
         difficulty='MEDIUM',
         question_text='A buck converter has input voltage 24V and duty cycle 0.25. Find the output '
                        'voltage (ideal, continuous conduction mode).',
         given_values='Vin = 24V, D = 0.25',
         option_a='3 V', option_b='6 V', option_c='12 V', option_d='18 V',
         correct_option='B',
         explanation='For an ideal buck converter, Vout = D × Vin = 0.25 × 24 = 6V.',
         formula_hint='Vout = D × Vin', points=15),
    dict(title='Full-Wave Rectifier Ripple', topic='POWER_ELECTRONICS', problem_type='THEORY',
         difficulty='HARD',
         question_text='Compared to a half-wave rectifier, a full-wave rectifier has:',
         option_a='Higher ripple frequency and higher ripple factor',
         option_b='Lower ripple frequency and lower ripple factor',
         option_c='Higher ripple frequency and lower ripple factor',
         option_d='Same ripple frequency and same ripple factor',
         correct_option='C',
         explanation='Full-wave rectification doubles the ripple frequency (2f) and reduces the '
                     'ripple factor since both half-cycles are utilized, giving smoother DC output.',
         formula_hint='Ripple factor ∝ 1 / (utilized cycles)', points=20),

    # ---------------- RENEWABLE ENERGY ----------------
    dict(title='Solar PV Cell Material', topic='RENEWABLE_ENERGY', problem_type='THEORY',
         difficulty='EASY',
         question_text='Which semiconductor material is most commonly used in commercial solar PV cells?',
         option_a='Gallium Arsenide', option_b='Silicon', option_c='Germanium', option_d='Cadmium Telluride',
         correct_option='B',
         explanation='Silicon (both mono- and polycrystalline) dominates commercial solar PV '
                     'manufacturing due to its abundance, stability, and mature fabrication process.',
         formula_hint='N/A — conceptual', points=10),
    dict(title='Wind Turbine Power Output', topic='RENEWABLE_ENERGY', problem_type='NUMERICAL',
         difficulty='HARD',
         question_text='A wind turbine has blade radius 20m, air density $1.2\\ kg/m^3$, wind speed '
                        '10 m/s, and power coefficient $C_p = 0.4$. Find the extractable power '
                        '(use $P = \\frac{1}{2}\\rho A v^3 C_p$).',
         given_values='r = 20m, ρ = 1.2 kg/m³, v = 10 m/s, Cp = 0.4',
         option_a='≈150.8 kW', option_b='≈301.6 kW', option_c='≈502.7 kW', option_d='≈603.2 kW',
         correct_option='B',
         explanation='A = πr² = π(20)² ≈ 1256.6 m². P = 0.5 × 1.2 × 1256.6 × 1000 × 0.4 ≈ 301,600 W '
                     '≈ 301.6 kW.',
         formula_hint='P = ½ρAv³Cp, A = πr²', points=20),
    dict(title='MPPT Purpose', topic='RENEWABLE_ENERGY', problem_type='THEORY',
         difficulty='MEDIUM',
         question_text='The purpose of Maximum Power Point Tracking (MPPT) in a solar system is to:',
         option_a='Reduce panel temperature', option_b='Maximize energy extraction from the PV array',
         option_c='Store excess energy', option_d='Regulate grid frequency',
         correct_option='B',
         explanation='MPPT continuously adjusts the electrical operating point of the PV array to '
                     'extract the maximum possible power under varying irradiance and temperature.',
         formula_hint='Tracks the knee of the P-V curve', points=15),

    # ---------------- CONTROL SYSTEMS ----------------
    dict(title='Stability from Pole Location', topic='CONTROL_SYSTEMS', problem_type='THEORY',
         difficulty='MEDIUM',
         question_text='A linear time-invariant system is stable if all poles of its transfer '
                        'function lie:',
         option_a='On the imaginary axis', option_b='In the right half of the s-plane',
         option_c='In the left half of the s-plane', option_d='At the origin',
         correct_option='C',
         explanation='For BIBO stability of an LTI system, all poles must lie strictly in the left '
                     'half of the s-plane (negative real parts).',
         formula_hint='Re(pole) < 0 for all poles', points=15),
    dict(title='Second Order System Damping', topic='CONTROL_SYSTEMS', problem_type='NUMERICAL',
         difficulty='HARD',
         question_text='A second-order system has natural frequency $\\omega_n = 5\\ rad/s$ and '
                        'damping ratio $\\zeta = 0.5$. Find the damped frequency $\\omega_d$.',
         given_values='ωn = 5 rad/s, ζ = 0.5',
         option_a='2.5 rad/s', option_b='3.75 rad/s', option_c='4.33 rad/s', option_d='5 rad/s',
         correct_option='C',
         explanation='ωd = ωn√(1 − ζ²) = 5 × √(1 − 0.25) = 5 × √0.75 ≈ 5 × 0.866 ≈ 4.33 rad/s.',
         formula_hint='ωd = ωn√(1 − ζ²)', points=20),
    dict(title='PID Controller — Integral Term', topic='CONTROL_SYSTEMS', problem_type='THEORY',
         difficulty='EASY',
         question_text='In a PID controller, the integral term primarily helps to:',
         option_a='Increase overshoot', option_b='Eliminate steady-state error',
         option_c='Increase rise time', option_d='Reduce system order',
         correct_option='B',
         explanation='The integral term accumulates past error over time, driving steady-state '
                     'error to zero for step inputs.',
         formula_hint='u(t) includes Ki∫e(t)dt', points=10),

    # ---------------- EMBEDDED AND IOT ----------------
    dict(title='Microcontroller vs Microprocessor', topic='EMBEDDED_IOT', problem_type='THEORY',
         difficulty='EASY',
         question_text='A key difference between a microcontroller and a microprocessor is that a '
                        'microcontroller:',
         option_a='Has no CPU', option_b='Integrates CPU, memory, and I/O on a single chip',
         option_c='Cannot execute instructions', option_d='Requires an external CPU always',
         correct_option='B',
         explanation='A microcontroller integrates a CPU core along with RAM, ROM, and I/O '
                     'peripherals on one chip, making it self-contained for embedded applications.',
         formula_hint='N/A — conceptual', points=10),
    dict(title='UART Baud Rate Timing', topic='EMBEDDED_IOT', problem_type='NUMERICAL',
         difficulty='MEDIUM',
         question_text='At a UART baud rate of 9600 bps, how long does it take to transmit one bit?',
         given_values='Baud rate = 9600 bps',
         option_a='≈10.4 µs', option_b='≈104.2 µs', option_c='≈1.04 ms', option_d='≈10.4 ms',
         correct_option='B',
         explanation='Bit time = 1/baud rate = 1/9600 ≈ 0.0001042 s ≈ 104.2 µs.',
         formula_hint='T_bit = 1 / baud_rate', points=15),
    dict(title='MQTT in IoT', topic='EMBEDDED_IOT', problem_type='THEORY',
         difficulty='MEDIUM',
         question_text='MQTT is widely used in IoT systems mainly because it is:',
         option_a='A heavyweight protocol requiring high bandwidth',
         option_b='A lightweight publish-subscribe protocol suited to constrained devices',
         option_c='Exclusively used for video streaming',
         option_d='A hardware communication standard, not a protocol',
         correct_option='B',
         explanation='MQTT is a lightweight publish-subscribe messaging protocol designed for '
                     'low-bandwidth, high-latency, or unreliable networks common in IoT deployments.',
         formula_hint='N/A — conceptual', points=15),

    # ============ ADDITIONAL QUESTIONS — BASIC ELECTRICAL ============
    dict(title='Parallel Resistor Combination', topic='BASIC_ELECTRICAL', problem_type='NUMERICAL',
         difficulty='MEDIUM',
         question_text='Two resistors of $6\\Omega$ and $12\\Omega$ are connected in parallel. '
                        'Find the equivalent resistance.',
         given_values='R1 = 6Ω, R2 = 12Ω',
         option_a='2 Ω', option_b='4 Ω', option_c='9 Ω', option_d='18 Ω',
         correct_option='B',
         explanation='R_eq = (R1×R2)/(R1+R2) = (6×12)/18 = 72/18 = 4Ω.',
         formula_hint='R_eq = (R1 R2)/(R1 + R2)', points=15),
    dict(title='Capacitor Energy Storage', topic='BASIC_ELECTRICAL', problem_type='NUMERICAL',
         difficulty='MEDIUM',
         question_text='A $100\\mu F$ capacitor is charged to 50V. Calculate the energy stored.',
         given_values='C = 100µF, V = 50V',
         option_a='0.125 J', option_b='0.25 J', option_c='2.5 J', option_d='5 J',
         correct_option='A',
         explanation='E = ½CV² = 0.5 × 100×10⁻⁶ × 2500 = 0.125 J.',
         formula_hint='E = ½CV²', points=15),
    dict(title='AC vs DC', topic='BASIC_ELECTRICAL', problem_type='THEORY', difficulty='EASY',
         question_text='In an alternating current (AC) supply, the direction of current:',
         option_a='Remains constant', option_b='Reverses periodically',
         option_c='Is always zero', option_d='Flows only in one direction',
         correct_option='B',
         explanation='AC periodically reverses direction, following a sinusoidal (or other periodic) '
                     'waveform, unlike DC which flows in one constant direction.',
         formula_hint='N/A — conceptual', points=10),
    dict(title='RMS Value of Sinusoid', topic='BASIC_ELECTRICAL', problem_type='NUMERICAL',
         difficulty='EASY',
         question_text='A sinusoidal voltage has a peak value of 220V. Find its RMS value.',
         given_values='Vm = 220V',
         option_a='110 V', option_b='155.6 V', option_c='190 V', option_d='220 V',
         correct_option='B',
         explanation='V_rms = Vm/√2 = 220/1.414 ≈ 155.6V.',
         formula_hint='V_rms = Vm / √2', points=10),
    dict(title='Kirchhoff Voltage Law Basis', topic='BASIC_ELECTRICAL', problem_type='THEORY',
         difficulty='EASY',
         question_text="Kirchhoff's Voltage Law (KVL) is based on the conservation of:",
         option_a='Charge', option_b='Energy', option_c='Mass', option_d='Current',
         correct_option='B',
         explanation='KVL states that the algebraic sum of voltages around a closed loop is zero, '
                     'which follows from the conservation of energy.',
         formula_hint='ΣV = 0 around a closed loop', points=10),

    # ============ ADDITIONAL QUESTIONS — CIRCUIT THEORY ============
    dict(title='Norton Equivalent Current', topic='CIRCUIT_THEORY', problem_type='NUMERICAL',
         difficulty='MEDIUM',
         question_text='A circuit has a Thevenin voltage of 24V and Thevenin resistance of $8\\Omega$. '
                        'Find the Norton equivalent current.',
         given_values='Vth = 24V, Rth = 8Ω',
         option_a='1 A', option_b='2 A', option_c='3 A', option_d='4 A',
         correct_option='C',
         explanation='I_N = V_th / R_th = 24/8 = 3A. Norton current equals Thevenin voltage divided '
                     'by Thevenin resistance.',
         formula_hint='I_N = V_th / R_th', points=15),
    dict(title='Maximum Power Transfer', topic='CIRCUIT_THEORY', problem_type='THEORY',
         difficulty='MEDIUM',
         question_text='Maximum power is transferred from source to load when the load resistance is:',
         option_a='Zero', option_b='Equal to source resistance',
         option_c='Infinite', option_d='Twice the source resistance',
         correct_option='B',
         explanation='The Maximum Power Transfer Theorem states max power is delivered to the load '
                     'when R_load = R_source (source internal resistance).',
         formula_hint='R_load = R_source for max power', points=15),
    dict(title='Node Voltage Method', topic='CIRCUIT_THEORY', problem_type='NUMERICAL',
         difficulty='HARD',
         question_text='In a single-node circuit, a $2A$ current source feeds a node connected to '
                        'ground through a $5\\Omega$ resistor. Find the node voltage.',
         given_values='I = 2A, R = 5Ω',
         option_a='2.5 V', option_b='5 V', option_c='10 V', option_d='20 V',
         correct_option='C',
         explanation='By KCL, all 2A flows through the 5Ω resistor to ground: V = IR = 2 × 5 = 10V.',
         formula_hint='V_node = I × R (single resistor to ground)', points=20),
    dict(title='Mesh Analysis Basis', topic='CIRCUIT_THEORY', problem_type='THEORY',
         difficulty='EASY',
         question_text='Mesh analysis in circuit theory is fundamentally an application of:',
         option_a="KCL only", option_b="KVL only", option_c='Both KCL and KVL', option_d='Ohm\'s Law only',
         correct_option='B',
         explanation="Mesh (loop) analysis writes KVL equations around each independent loop to "
                     "solve for mesh currents.",
         formula_hint='Loop equations use KVL', points=10),
    dict(title='RC Time Constant', topic='CIRCUIT_THEORY', problem_type='NUMERICAL',
         difficulty='MEDIUM',
         question_text='An RC circuit has $R = 2k\\Omega$ and $C = 5\\mu F$. Find the time constant.',
         given_values='R = 2kΩ, C = 5µF',
         option_a='1 ms', option_b='5 ms', option_c='10 ms', option_d='20 ms',
         correct_option='C',
         explanation='τ = RC = 2000 × 5×10⁻⁶ = 0.01 s = 10 ms.',
         formula_hint='τ = R × C', points=15),

    # ============ ADDITIONAL QUESTIONS — ELECTRONICS AND VLSI ============
    dict(title='BJT Current Gain', topic='ELECTRONICS_VLSI', problem_type='NUMERICAL',
         difficulty='MEDIUM',
         question_text='A BJT has base current 20µA and collector current 2mA. Find the current gain β.',
         given_values='I_B = 20µA, I_C = 2mA',
         option_a='10', option_b='50', option_c='100', option_d='200',
         correct_option='C',
         explanation='β = I_C / I_B = 2×10⁻³ / 20×10⁻⁶ = 100.',
         formula_hint='β = I_C / I_B', points=15),
    dict(title='Op-Amp Ideal Characteristics', topic='ELECTRONICS_VLSI', problem_type='THEORY',
         difficulty='EASY',
         question_text='An ideal operational amplifier has:',
         option_a='Zero input impedance, infinite output impedance',
         option_b='Infinite input impedance, zero output impedance',
         option_c='Finite gain and finite bandwidth',
         option_d='Zero open-loop gain',
         correct_option='B',
         explanation='Ideal op-amps have infinite input impedance (draws no input current) and zero '
                     'output impedance (acts as a perfect voltage source).',
         formula_hint='Zin → ∞, Zout → 0, Av → ∞', points=10),
    dict(title='Logic Gate NAND Universality', topic='ELECTRONICS_VLSI', problem_type='THEORY',
         difficulty='MEDIUM',
         question_text='The NAND gate is called a "universal gate" because:', 
         option_a='It consumes zero power',
         option_b='Any logic function can be implemented using only NAND gates',
         option_c='It only works with analog signals',
         option_d='It has the fastest switching speed of all gates',
         correct_option='B',
         explanation='NAND (and NOR) gates are functionally complete — AND, OR, NOT, and any Boolean '
                     'function can be built using combinations of NAND gates alone.',
         formula_hint='N/A — conceptual', points=15),
    dict(title='Zener Diode Voltage Regulation', topic='ELECTRONICS_VLSI', problem_type='NUMERICAL',
         difficulty='MEDIUM',
         question_text='A Zener diode with breakdown voltage 5.6V regulates a supply. If the load '
                        'draws 10mA and series resistor is $100\\Omega$ with a 9V source, find the '
                        'Zener current.',
         given_values='Vz = 5.6V, Vs = 9V, R = 100Ω, I_load = 10mA',
         option_a='4 mA', option_b='24 mA', option_c='34 mA', option_d='44 mA',
         correct_option='A',
         explanation='Total current I_total = (Vs − Vz)/R = (9 − 5.6)/100 = 34mA. Zener current = '
                     'I_total − I_load = 34 − 10 = 24mA... recompute: 3.4/100=0.034A=34mA; '
                     '34mA − 10mA = 24mA.',
         formula_hint='I_R = (Vs − Vz)/R, I_zener = I_R − I_load', points=20),
    dict(title='Sampling Theorem', topic='ELECTRONICS_VLSI', problem_type='THEORY',
         difficulty='MEDIUM',
         question_text='According to the Nyquist sampling theorem, a signal with max frequency '
                        '$f_m$ must be sampled at a rate:',
         option_a='Equal to fm', option_b='At least 2fm', option_c='At most fm/2', option_d='Exactly fm/2',
         correct_option='B',
         explanation='To avoid aliasing, the sampling rate must be at least twice the highest '
                     'frequency component in the signal (Nyquist rate = 2fm).',
         formula_hint='fs ≥ 2 fm', points=15),

    # ============ ADDITIONAL QUESTIONS — ELECTRICAL MACHINES ============
    dict(title='Synchronous Speed Formula', topic='ELECTRICAL_MACHINES', problem_type='NUMERICAL',
         difficulty='EASY',
         question_text='Find the synchronous speed of a 4-pole induction motor supplied at 50Hz.',
         given_values='P = 4, f = 50Hz',
         option_a='750 RPM', option_b='1000 RPM', option_c='1500 RPM', option_d='3000 RPM',
         correct_option='C',
         explanation='Ns = 120f/P = 120×50/4 = 1500 RPM.',
         formula_hint='Ns = 120f / P', points=10),
    dict(title='DC Generator Types', topic='ELECTRICAL_MACHINES', problem_type='THEORY',
         difficulty='MEDIUM',
         question_text='In a shunt DC generator, the field winding is connected:',
         option_a='In series with the armature', option_b='In parallel with the armature',
         option_c='Independently, with a separate supply', option_d='Not connected to the armature at all',
         correct_option='B',
         explanation='In a shunt generator, the field winding (high resistance, many turns) is '
                     'connected in parallel (shunt) with the armature.',
         formula_hint='N/A — conceptual', points=15),
    dict(title='Transformer Efficiency', topic='ELECTRICAL_MACHINES', problem_type='NUMERICAL',
         difficulty='HARD',
         question_text='A transformer delivers 8kW output while consuming 8.5kW input. Find its efficiency.',
         given_values='P_out = 8kW, P_in = 8.5kW',
         option_a='85.5%', option_b='90.6%', option_c='94.1%', option_d='97.2%',
         correct_option='C',
         explanation='Efficiency = (P_out/P_in) × 100 = (8/8.5) × 100 ≈ 94.1%.',
         formula_hint='η = (P_out / P_in) × 100', points=20),
    dict(title='Starting Torque of Induction Motor', topic='ELECTRICAL_MACHINES', problem_type='THEORY',
         difficulty='MEDIUM',
         question_text='A star-delta starter is used for induction motors mainly to:',
         option_a='Increase starting torque', option_b='Reduce starting current',
         option_c='Increase running speed', option_d='Reverse the direction of rotation',
         correct_option='B',
         explanation='Star-delta starting reduces the voltage applied per phase at start (to 1/√3), '
                     'cutting starting current to about 1/3 of direct-on-line starting current.',
         formula_hint='I_star = I_delta / 3 (approx)', points=15),
    dict(title='Armature Reaction', topic='ELECTRICAL_MACHINES', problem_type='THEORY',
         difficulty='HARD',
         question_text='Armature reaction in a DC machine refers to:',
         option_a='Reaction of the commutator with brushes',
         option_b='The effect of armature current on the main field flux distribution',
         option_c='Heat generated in the armature winding',
         option_d='Mechanical vibration of the rotor',
         correct_option='B',
         explanation='Armature reaction is the distorting and weakening effect that the '
                     'armature-produced magnetomotive force has on the main field flux.',
         formula_hint='N/A — conceptual', points=20),

    # ============ ADDITIONAL QUESTIONS — POWER ELECTRONICS ============
    dict(title='Boost Converter Output', topic='POWER_ELECTRONICS', problem_type='NUMERICAL',
         difficulty='MEDIUM',
         question_text='A boost converter has input voltage 10V and duty cycle 0.5. Find the ideal '
                        'output voltage.',
         given_values='Vin = 10V, D = 0.5',
         option_a='5 V', option_b='10 V', option_c='20 V', option_d='40 V',
         correct_option='C',
         explanation='For an ideal boost converter, Vout = Vin / (1 − D) = 10 / 0.5 = 20V.',
         formula_hint='Vout = Vin / (1 − D)', points=15),
    dict(title='IGBT Application', topic='POWER_ELECTRONICS', problem_type='THEORY', difficulty='EASY',
         question_text='IGBTs are widely preferred in medium-to-high power applications because they combine:',
         option_a='BJT input characteristics with MOSFET output characteristics',
         option_b='MOSFET-like gate control with BJT-like low conduction loss',
         option_c='Only the properties of a diode',
         option_d='Pure thyristor latching behavior',
         correct_option='B',
         explanation='IGBTs combine the easy voltage-controlled gate of a MOSFET with the low '
                     'on-state conduction losses characteristic of a BJT.',
         formula_hint='N/A — conceptual', points=10),
    dict(title='PWM Switching Frequency', topic='POWER_ELECTRONICS', problem_type='THEORY',
         difficulty='MEDIUM',
         question_text='Increasing the PWM switching frequency in a power converter generally:',
         option_a='Increases passive component size (inductors/capacitors)',
         option_b='Reduces passive component size but increases switching losses',
         option_c='Has no effect on component size or losses',
         option_d='Only affects the output voltage polarity',
         correct_option='B',
         explanation='Higher switching frequency allows smaller inductors/capacitors for the same '
                     'ripple, but increases switching losses in the semiconductor devices.',
         formula_hint='L, C ∝ 1/f_sw (approx); P_switching ∝ f_sw', points=15),
    dict(title='Three-Phase Rectifier Ripple Frequency', topic='POWER_ELECTRONICS', problem_type='NUMERICAL',
         difficulty='HARD',
         question_text='A three-phase full-wave (6-pulse) rectifier is supplied at 50Hz. Find the '
                        'output ripple frequency.',
         given_values='f_supply = 50Hz, pulse number = 6',
         option_a='50 Hz', option_b='100 Hz', option_c='150 Hz', option_d='300 Hz',
         correct_option='D',
         explanation='Ripple frequency = pulse number × supply frequency = 6 × 50 = 300Hz.',
         formula_hint='f_ripple = pulse_number × f_supply', points=20),
    dict(title='Snubber Circuit Purpose', topic='POWER_ELECTRONICS', problem_type='THEORY',
         difficulty='MEDIUM',
         question_text='A snubber circuit is used across power semiconductor switches primarily to:',
         option_a='Increase switching speed indefinitely',
         option_b='Protect against voltage/current spikes during switching transients',
         option_c='Increase the DC output voltage',
         option_d='Replace the need for heat sinks',
         correct_option='B',
         explanation='Snubber circuits (RC or RCD) suppress voltage and current transients during '
                     'turn-on/turn-off, protecting switches from stress and EMI.',
         formula_hint='N/A — conceptual', points=15),

    # ============ ADDITIONAL QUESTIONS — RENEWABLE ENERGY ============
    dict(title='Solar Panel Series Connection', topic='RENEWABLE_ENERGY', problem_type='NUMERICAL',
         difficulty='EASY',
         question_text='Four identical solar panels, each rated 12V, are connected in series. '
                        'Find the total output voltage.',
         given_values='V_panel = 12V, n = 4, series',
         option_a='12 V', option_b='24 V', option_c='36 V', option_d='48 V',
         correct_option='D',
         explanation='In series, voltages add: V_total = 4 × 12 = 48V.',
         formula_hint='V_series = n × V_panel', points=10),
    dict(title='Fuel Cell Basic Principle', topic='RENEWABLE_ENERGY', problem_type='THEORY',
         difficulty='MEDIUM',
         question_text='A hydrogen fuel cell generates electricity primarily through:',
         option_a='Combustion of hydrogen gas',
         option_b='An electrochemical reaction between hydrogen and oxygen',
         option_c='Mechanical rotation of a turbine',
         option_d='Nuclear fission',
         correct_option='B',
         explanation='Fuel cells convert chemical energy directly to electrical energy via an '
                     'electrochemical reaction between hydrogen and oxygen, producing water as byproduct.',
         formula_hint='N/A — conceptual', points=15),
    dict(title='Battery Storage Capacity', topic='RENEWABLE_ENERGY', problem_type='NUMERICAL',
         difficulty='MEDIUM',
         question_text='A battery bank is rated 200Ah at 24V. Find its total energy storage capacity.',
         given_values='Capacity = 200Ah, V = 24V',
         option_a='0.83 kWh', option_b='4.8 kWh', option_c='8.3 kWh', option_d='48 kWh',
         correct_option='B',
         explanation='Energy = Ah × V = 200 × 24 = 4800 Wh = 4.8 kWh.',
         formula_hint='Energy (Wh) = Ah × V', points=15),
    dict(title='Grid-Tied vs Off-Grid Solar', topic='RENEWABLE_ENERGY', problem_type='THEORY',
         difficulty='EASY',
         question_text='A grid-tied solar system, unlike an off-grid system, typically:',
         option_a='Requires a large battery bank as its primary component',
         option_b='Can export excess power to the utility grid without batteries',
         option_c='Cannot use an inverter',
         option_d='Only works during a power outage',
         correct_option='B',
         explanation='Grid-tied systems synchronize with the utility grid and can feed excess '
                     'generated power back into it, generally without requiring battery storage.',
         formula_hint='N/A — conceptual', points=10),
    dict(title='Capacity Factor', topic='RENEWABLE_ENERGY', problem_type='NUMERICAL',
         difficulty='HARD',
         question_text='A wind farm rated at 10MW produces an average of 3MW over a year. Find its capacity factor.',
         given_values='Rated = 10MW, Average output = 3MW',
         option_a='10%', option_b='20%', option_c='30%', option_d='40%',
         correct_option='C',
         explanation='Capacity factor = (Average output / Rated capacity) × 100 = (3/10) × 100 = 30%.',
         formula_hint='CF = (P_avg / P_rated) × 100', points=20),

    # ============ ADDITIONAL QUESTIONS — CONTROL SYSTEMS ============
    dict(title='Open-Loop vs Closed-Loop', topic='CONTROL_SYSTEMS', problem_type='THEORY',
         difficulty='EASY',
         question_text='A closed-loop (feedback) control system, unlike an open-loop system:',
         option_a='Has no output', option_b='Uses feedback to compare output with reference input',
         option_c='Cannot be automated', option_d='Is always unstable',
         correct_option='B',
         explanation='Closed-loop systems measure the output and feed it back to compare against the '
                     'reference, using the error to correct system behavior — improving accuracy.',
         formula_hint='N/A — conceptual', points=10),
    dict(title='Routh-Hurwitz Criterion', topic='CONTROL_SYSTEMS', problem_type='THEORY',
         difficulty='HARD',
         question_text='The Routh-Hurwitz criterion is used to determine:',
         option_a='The exact roots of the characteristic equation',
         option_b='System stability without explicitly solving for the roots',
         option_c='The transfer function of a system',
         option_d='The steady-state error only',
         correct_option='B',
         explanation="Routh-Hurwitz determines how many roots of the characteristic equation lie in "
                     "the right-half s-plane — establishing stability — without solving for the roots directly.",
         formula_hint='Sign changes in first column of Routh array = RHP roots', points=20),
    dict(title='Steady-State Error — Type 0 System', topic='CONTROL_SYSTEMS', problem_type='NUMERICAL',
         difficulty='HARD',
         question_text='A type-0 unity feedback system has open-loop gain $K = 9$. Find the steady-state '
                        'error for a unit step input.',
         given_values='K = 9, Type-0 system, unit step input',
         option_a='0', option_b='0.1', option_c='0.5', option_d='0.9',
         correct_option='B',
         explanation='For a type-0 system, e_ss = 1/(1+Kp) where Kp = K = 9. So e_ss = 1/(1+9) = 0.1.',
         formula_hint='e_ss = 1 / (1 + Kp)', points=20),
    dict(title='Bode Plot Gain Margin', topic='CONTROL_SYSTEMS', problem_type='THEORY',
         difficulty='MEDIUM',
         question_text='On a Bode plot, the gain margin is measured at the frequency where:',
         option_a='The magnitude plot crosses 0 dB', option_b='The phase plot crosses −180°',
         option_c='The magnitude is at its maximum', option_d='The frequency is zero',
         correct_option='B',
         explanation='Gain margin is the amount of gain increase/decrease (in dB) required to make '
                     'the system marginally stable, measured at the phase crossover frequency (−180°).',
         formula_hint='GM measured at phase = −180°', points=15),
    dict(title='Transfer Function of Integrator', topic='CONTROL_SYSTEMS', problem_type='NUMERICAL',
         difficulty='EASY',
         question_text='Find the transfer function of a pure integrator block with gain constant K.',
         given_values='Integrator with gain K',
         option_a='K', option_b='Ks', option_c='K/s', option_d='K/s²',
         correct_option='C',
         explanation='An integrator in the Laplace domain has transfer function K/s, since '
                     'integration corresponds to division by s.',
         formula_hint='∫x dt ↔ X(s)/s', points=10),

    # ============ ADDITIONAL QUESTIONS — EMBEDDED AND IOT ============
    dict(title='ADC Resolution', topic='EMBEDDED_IOT', problem_type='NUMERICAL', difficulty='MEDIUM',
         question_text='A 10-bit ADC has a reference voltage of 5V. Find its resolution (smallest '
                        'detectable voltage step).',
         given_values='n = 10 bits, Vref = 5V',
         option_a='2.44 mV', option_b='4.88 mV', option_c='9.76 mV', option_d='19.5 mV',
         correct_option='B',
         explanation='Resolution = Vref / (2ⁿ − 1) = 5 / (1024 − 1) = 5/1023 ≈ 4.89 mV ≈ 4.88mV.',
         formula_hint='Resolution = Vref / (2ⁿ − 1)', points=15),
    dict(title='Interrupt vs Polling', topic='EMBEDDED_IOT', problem_type='THEORY', difficulty='MEDIUM',
         question_text='Compared to polling, using interrupts in embedded systems is generally more efficient because:',
         option_a='The CPU continuously checks device status in a loop',
         option_b='The CPU is freed to do other tasks until a device signals it needs attention',
         option_c='Interrupts require more CPU cycles per check',
         option_d='Interrupts can only be used with a single peripheral',
         correct_option='B',
         explanation='Interrupts let the CPU perform other work and respond only when a peripheral '
                     'signals an event, unlike polling which wastes cycles repeatedly checking status.',
         formula_hint='N/A — conceptual', points=15),
    dict(title='I2C Bus Lines', topic='EMBEDDED_IOT', problem_type='THEORY', difficulty='EASY',
         question_text='The I2C communication protocol uses how many signal lines (excluding ground/power)?',
         option_a='1', option_b='2', option_c='3', option_d='4',
         correct_option='B',
         explanation='I2C uses two lines: SDA (Serial Data) and SCL (Serial Clock), making it a '
                     'compact two-wire bus for multiple devices.',
         formula_hint='SDA + SCL = 2 lines', points=10),
    dict(title='Watchdog Timer Purpose', topic='EMBEDDED_IOT', problem_type='THEORY', difficulty='MEDIUM',
         question_text='A watchdog timer in an embedded system is primarily used to:',
         option_a='Increase clock speed', option_b='Reset the system if software hangs or crashes',
         option_c='Measure ambient temperature', option_d='Encrypt communication data',
         correct_option='B',
         explanation='A watchdog timer resets the microcontroller if the software fails to '
                     'periodically "kick" (reset) it — recovering from hangs or infinite loops.',
         formula_hint='N/A — conceptual', points=15),
    dict(title='IoT Edge Computing Latency', topic='EMBEDDED_IOT', problem_type='NUMERICAL',
         difficulty='HARD',
         question_text='A sensor reading takes 5ms to process at the edge versus 45ms round-trip to '
                        'the cloud. Find the percentage latency reduction using edge computing.',
         given_values='Edge = 5ms, Cloud = 45ms',
         option_a='71.1%', option_b='80%', option_c='88.9%', option_d='95%',
         correct_option='C',
         explanation='Reduction = (45 − 5)/45 × 100 = 40/45 × 100 ≈ 88.9%.',
         formula_hint='% reduction = (T_cloud − T_edge)/T_cloud × 100', points=20),
]


class Command(BaseCommand):
    help = 'Seed the database with sample EEE MCQ questions across all 8 Volts Lab topics.'

    def handle(self, *args, **options):
        created_count = 0
        for q in SEED_QUESTIONS:
            obj, created = Question.objects.get_or_create(
                title=q['title'], topic=q['topic'], defaults=q
            )
            if created:
                created_count += 1
        self.stdout.write(self.style.SUCCESS(
            f'Seed complete. {created_count} new questions created '
            f'(total in DB: {Question.objects.count()}).'
        ))
